### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by DutchPete** [Sh00Fly/logseq-bear-cub-theme#1]
I love this theme so much I decided to give it an extra “bearish” touch by giving page titles a Bear red color and the font white - see screenshot. That is for Light mode.

<img width="284" alt="title" src="https://github.com/Sh00Fly/logseq-bear-cub-theme/assets/10794265/5f00f714-e5da-4b83-b0de-28ba701e7401">

For Dark mode I want the font to remain white, but the background to be blue (--cl-picton). In my `custom.css` I have this:

```css
.white-theme, h1.title,
html[data-theme=light] {
  background-color: var(--cl-valencia);
}

.dark-theme, h1.title,
html[data-theme=dark] {
  background-color: #49a8f8 !important;
}
```

However, I then get the blue background in Light mode too, even if I put the white-theme block below the dark-theme block. So, for now, I have disabled the dark-theme block.

I must be doing something wrong but I don't know what.
